### ISSUE TITLE
TPU 95 "bridging" settings

### ISSUE THREAD

**Issue by synsuiter** [SynDaverCO/symple-slicer#102]
**Describe the bug**
When I export the TPU 95 Profile I get different Bridging Speed settings than in the direct profile .toml file. 

**Details**
 - SympleSlicer Version: 1.0.8
 - Browser [e.g. chrome, safari] ; Chrome

**To Reproduce**
Apply Syndaver Axi Machine and TPU Shore hardness 95 profile. then g and export that profile. Confirm by comparing to the git hub direct profile file. 

**Expected behavior**
To export the settings that were set initially. 

**Screenshots**
![Capture](https://user-images.githubusercontent.com/65256117/89455332-64018280-d71f-11ea-828e-8ee45ee2a656.JPG)

**Comment by synsuiter** [comment]
Also Material_final_print_temp and Material_initial_print_temp settings exporting incorrectly. 

![Capture2](https://user-images.githubusercontent.com/65256117/89455765-09b4f180-d720-11ea-9484-bc7719cb7337.JPG)

**Comment by marciot** [comment]
Have you refreshed since I put in a fix for #101? Probably same thing.

**Comment by synsuiter** [comment]
I thought I had refreshed but it just updated for me, looks good.
