### ISSUE TITLE
Adding Parts to the bed

### ISSUE THREAD

**Issue by synsuiter** [SynDaverCO/symple-slicer#104]
**Describe the bug**
When adding parts to the bed, the 1st 3 have no issue, but addition 4-6 do not appear to have been added, THEY ARE ADDED, but they have been placed over the top of the other previously aided parts. Then when I add #7, they all snap to an area showing them but they are still overlapping. 

**Details**
 - SympleSlicer Version: 1.0.8
 - Browser: Chrome

**To Reproduce**
I used the model for our spool arm, this happens more with larger parts. 
All I did was add the parts, the application of machine and profile settings do not seam to make a differece. 
Please see images bellow for process. 

**Expected behavior**
The parts to be added next to one another or off the bed (if they don't fit on it) instead of over the top of one another. 

**Screenshots**
![BUG2-IMG-1](https://user-images.githubusercontent.com/65256117/89915994-48c9c380-dbb4-11ea-8437-f1dce1b60027.JPG)
![BUG2-IMG-2](https://user-images.githubusercontent.com/65256117/89915997-49625a00-dbb4-11ea-810f-140be0cb7468.JPG)
![BUG2-IMG-3](https://user-images.githubusercontent.com/65256117/89915998-49625a00-dbb4-11ea-8a6e-2b522df710c9.JPG)
![BUG2-IMG-4](https://user-images.githubusercontent.com/65256117/89916001-49625a00-dbb4-11ea-901d-5c4ffd788b05.JPG)
![BUG2-IMG-5](https://user-images.githubusercontent.com/65256117/89916003-49faf080-dbb4-11ea-8d32-40b46087fba4.JPG)
![BUG2-IMG-6](https://user-images.githubusercontent.com/65256117/89916004-49faf080-dbb4-11ea-9cf7-440fae6bf12c.JPG)
![BUG2-IMG-7](https://user-images.githubusercontent.com/65256117/89916005-49faf080-dbb4-11ea-9bf6-6ba6ded1abc7.JPG)

**Comment by marciot** [comment]
Please upload the STL files.

**Comment by marciot** [comment]
FYI, the packing algorithm used by Symple Slicer circumscribes all the parts in a circle and then tries to arrange those circles. Thus, it will never be able to pack long skinny parts next to each other. Those parts will always need to be manually adjusted in some way.

**Comment by marciot** [comment]
I'm a bit surprised this works for parts 1 through 3. It shouldn't work at all, TBH, because the circumscribed circles are overlapping. In cases like this, maybe Symple Slicer should tell the user automatic placement failed and they need to position the parts manually.

**Comment by marciot** [comment]
Arranging parts on a print bed is the sort of thing that is obvious to humans, but computers cannot do very well.

**Comment by synsuiter** [comment]
Can't upload the STL model, not supported, but I can sent it to you in an email if you would like. 

Good to know, I figured this was the case. We can use the info in this ticket to explain to customers its limitations in the future.
