### ISSUE TITLE
Parts shifting after profile application

### ISSUE THREAD

**Issue by synsuiter** [SynDaverCO/symple-slicer#105]
**Describe the bug**
When I add parts to the bed and get it centered, then apply a profile (either through the menu or an import), the parts then rearrange themselves back to the center, even if I had arranged them specifically or merely had them centered in a different way. This happens with multiple and stand alone parts. 

**Details**
 - SympleSlicer Version: 1. 0.8
 - Browser: Chrome

**To Reproduce**
Open Symple Slicer
Add part(s) to bed
Arrange them as desired
Apply your selected machine and print profile (or you can import a desired profile)
Watch the parts center and move around

**Expected behavior**
Part positions should not be adjusted when a profile is applied, they should remain stationary. 

**Screenshots**
![BUG3-IMG-1](https://user-images.githubusercontent.com/65256117/89923062-37d18000-dbbd-11ea-94c1-dfbde92b92fa.JPG)
![BUG3-IMG-2](https://user-images.githubusercontent.com/65256117/89923065-386a1680-dbbd-11ea-9260-18f31c704698.JPG)

**Comment by marciot** [comment]
@synsuiter: Loading a profile may change the bed dimensions, so right now it triggers the object placement routine. It may make sense to simply have an "automatically arrange bed" checkbox that starts out checked, but gets unchecked any time the user manually positions an object. That way Symple Slicer won't ever mess up what the user has done.

**Comment by synsuiter** [comment]
@marciot That seems like a good solution, we can place this on low priority, no direct complaints yet through tech support.

**Comment by synsuiter** [comment]
This has not yet been an issue for our customers. I am going to close this out.
