### ISSUE TITLE
Large Model

### ISSUE THREAD

**Issue by synsuiter** [SynDaverCO/symple-slicer#106]
**Describe the bug**
After applying a profile and watching the model move off the bed, when it is moved back on the bed, it still says it is unprintable. 

**Details**
 - SympleSlicer Version: 1.0.8
 - Browser: Chrome

**To Reproduce**
-Add large model
-Arrange Model on the bed
-Apply a profile and watch the model shift (this issue is already addressed in #105)
-Center your model and watch that it is still red.

**Expected behavior**
It should register as printable within the build space. 

**Screenshots**
![BUG-IMG-1](https://user-images.githubusercontent.com/65256117/89923762-4d937500-dbbe-11ea-8229-c9f832f75578.JPG)
![BUG-IMG-2](https://user-images.githubusercontent.com/65256117/89923767-4e2c0b80-dbbe-11ea-88da-a3c3a647ff52.JPG)
![BUG-IMG-3](https://user-images.githubusercontent.com/65256117/89923769-4e2c0b80-dbbe-11ea-9406-7eac8e213851.JPG)

Additional Info:
The only way to fix it is to move the model above the bed and letting it fall back to the build surface, that makes it printable again.

**Comment by synsuiter** [comment]
I can send you this model through email but i cant upload in in a comment here.

**Comment by marciot** [comment]
Change the file extension to .txt

**Comment by marciot** [comment]
@synsuiter: I believe this has been fixed in the latest beta.

**Comment by synsuiter** [comment]
This appears to be good to go.

I do want to note that when the model is sized down, it does not "center" on the bed, but is slightly off center. Since this is not a major issue, I am closing this out and will open a new ticket if the centering becomes an issue.
