### ISSUE TITLE
Mirror tool bug with lithophanes

### ISSUE THREAD

**Issue by synsuiter** [SynDaverCO/symple-slicer#107]
**Describe the bug**
When using the arrows on the object, the mirror tool does not mirror the object, it stretches it along the axis chosen. 

**Details**
 - SympleSlicer Version: 1.0.8
 - Browser [e.g. chrome, safari]: Chrome

**To Reproduce**
Load in a lithophane
Select the object
Click the Mirror tool
Use the arrows on the object to mirror the part
Watch it stretch
Side Note: when I used the same tool/button/axis a second time, it did mirror the part. 

**Expected behavior**
The part should mirror on the first click with those buttons

**Screenshots**
![bug-img-1](https://user-images.githubusercontent.com/65256117/90165692-499a5b00-dd56-11ea-8b8f-1f0e91e7f77c.JPG)
![bug-img-3](https://user-images.githubusercontent.com/65256117/90165713-50c16900-dd56-11ea-8e5e-d6abab968d31.JPG)
![bug-img-4](https://user-images.githubusercontent.com/65256117/90165722-54ed8680-dd56-11ea-87d9-9e4e2b9675c6.JPG)
![bug-img-5](https://user-images.githubusercontent.com/65256117/90165730-57e87700-dd56-11ea-90f2-dfa6003ebad0.JPG)
![bug-img-6](https://user-images.githubusercontent.com/65256117/90165734-5a4ad100-dd56-11ea-8681-69ce39b063cc.JPG)

**Comment by marciot** [comment]
This has been fixed in the beta.

**Comment by synsuiter** [comment]
Gracias!
