### ISSUE TITLE
Initial Layer Speed

### ISSUE THREAD

**Issue by synsuiter** [SynDaverCO/symple-slicer#112]
**Is your feature request related to a problem? Please describe.**
first layers are having a harder time sticking due to higher than usual default speed settings, control to the customer is needed for various adhesion methods. 

**Describe the solution you'd like**
A UI option for the First layer speed, independent of the "print speed" option. 

**Describe alternatives you've considered**
Slower speeds overall is the only alternative and we have chosen not to reduce speeds overall just for the 1st layers adhesion. 

**Additional context**

**Comment by marciot** [comment]
Please check this in the latest beta.

**Comment by marciot** [comment]
@synsuiter: Can this be closed?

**Comment by synsuiter** [comment]
This is good to go, thank you!
