### ISSUE TITLE
Setting Title Change in UI

### ISSUE THREAD

**Issue by synsuiter** [SynDaverCO/symple-slicer#119]
**Is your feature request related to a problem? Please describe.**
The current name for the setting that controls the Support distance in overhangs has a misleading title.

"support_xy_distance_overhang":
                {
                    "label": "**Minimum Support X/Y Distance**",
                    "description": "Distance of the support structure from the overhang in the X/Y directions. ",

**Describe the solution you'd like**
Rename that settings to read "Overhang Support X/Y Distance"

**Describe alternatives you've considered**
None.

**Additional context**
We may wat to consider suggesting this upstream.

**Comment by marciot** [comment]
Pushed a fix for this to beta.
