### ISSUE TITLE
Center Model with multiple on the bed

### ISSUE THREAD

**Issue by synsuiter** [SynDaverCO/symple-slicer#122]
**Describe the bug**
When trying to center an object with multiple objects on the build plate, it centers all objects. 

**Details**
 - SympleSlicer Version: Beta 1.0.11
 - Browser [e.g. chrome, safari]:  Chrome

**To Reproduce**
Load multiple objects
Move each to desired locations around the bed
select only one model and center it
Observe all other model move to grouped center

**Expected behavior**
Only the selected model should move to center

**Screenshots**
![center-issue-1](https://user-images.githubusercontent.com/65256117/95104627-463aa480-06f3-11eb-9dac-5f1aa5f8b1f5.PNG)
![center-issue-2](https://user-images.githubusercontent.com/65256117/95104630-476bd180-06f3-11eb-9ec0-4793e6ba7783.PNG)
![center-issue-3](https://user-images.githubusercontent.com/65256117/95104631-476bd180-06f3-11eb-9533-9626ff0ed784.PNG)

**Comment by marciot** [comment]
I cannot fix this. When you ask to center a model, it changes the position on the first object, but then has to run the packing algorithm to make sure the objects don't overlap. This causes all objects to gravitate towards the center of the bed.

**Comment by marciot** [comment]
I can ask the developer of the packing library whether there is a way to modify the algorithm so it doesn't try to pack things together, but merely avoid overlaps, but he may or may not be able to do this.

**Comment by synsuiter** [comment]
We could consider changing the wording of the tool to be "Center Objects" instead of specifying the selected one. If we cannot fix it, at least we can explain what it does more clearly.

**Comment by marciot** [comment]
So I looked at the code for the library. Even though the "packing" part is sort of an essential component for what the library is supposed to do (it's meant to pack circles close together, while we are sort of misusing it to prevent overlaps of parts), it looks like I might be able to turn off that functionality. I'm going to try out the modification and see what happens. It either will do exactly what we want, or sh*t will hit the fan and it won't work at all. We'll see.

**Comment by synsuiter** [comment]
I haven't noticed any other issues but the centering is still working the same. I can post images if needed but they will appear the same.

**Comment by synsuiter** [comment]
New update is looking good! no errors in centering, we will keep up testing and report back soon.

**Comment by marciot** [comment]
@synsuiter: Can this be closed?

**Comment by synsuiter** [comment]
Indeed! :D
