### ISSUE TITLE
Wifi ip remembering

### ISSUE THREAD

**Issue by synwest** [SynDaverCO/symple-slicer#127]
**Is your feature request related to a problem? Please describe.**
After getting the ip address of the printer after setting up wifi, you enter it into the designated field. There isnt a way to know that symple slicer will remember it

**Describe the solution you'd like**
A button in the wireless printing that saves the printer info for future printing.

**Comment by marciot** [comment]
@synwest: This is fully implemented in the web beta version now (the Symple Slicer Desktop has a slightly older code, so please look at the web one). Let me know what you think.
