### ISSUE TITLE
Additional Retraction Settings

### ISSUE THREAD

**Issue by thebelin** [SynDaverCO/symple-slicer#129]
Z hop on layer change would be nice to have. It allows for easy avoidance of previously printed parts and can really reduce stringing.
Z hop on retract would be super nice to have also.

Z hop distance on retract would be a float value representing the distance in mm to hop when retracted.
Z hop speed would be mm/s to travel and default at 10 mm/s

This could be added with post processing.

Existing Cura desktop handles this with a checkbox for retract on layer change, and a checkbox for z hop on retract, which enables the additional float settings.

**Comment by synsuiter** [comment]
@thebelin Thank you for your request. We are currently working to include more Settings options in the User Interface of Symple Slicer, including your requested settings. 
I am going to close out this ticket to clear up our ticket list for bug fixes but I want to assure you, We are on it!

Have a good one!
