### ISSUE TITLE
Save Option

### ISSUE THREAD

**Issue by stanreuben** [SynDaverCO/symple-slicer#131]
The save code option in Slicer beta version isn't available. Kindly check

![Screenshot 2021-01-06 at 2 23 45 PM](https://user-images.githubusercontent.com/75202932/103749014-f1c4ff00-502a-11eb-993f-c2325c49f578.png)

**Comment by marciot** [comment]
@stanreuben: Yeah, I pushed some broken code into the repo by mistake. I should have a fix in by the end of the week.

**Comment by stanreuben** [comment]
Sounds great
