### ISSUE TITLE
output format not set if "stl" appears in filename

### ISSUE THREAD

**Issue by SynWillinger** [SynDaverCO/symple-slicer#134]
**Describe the bug**
If the string "stl" appears in the filename of the input model, that stl string will be replaced with "gcode" and the ".stl" will remain as ".stl". 

**Details**
 - SympleSlicer Version: 1.0.158
 - Browser: Chrome

**To Reproduce**
1. Load a file with a name like "*stl.stl"
2. Slice and proceed to Print and Preview
3. Observe that the "Save as" string is now "*gcode.stl"

**Expected behavior**
section before the . in the filename should not be modified, and section after the . should be changed to gcode

**Screenshots**
![stl_filename_bug_1](https://user-images.githubusercontent.com/60902184/104623032-2ea67c80-564f-11eb-8ca7-f4cc7ca706c0.PNG)
![stl_filename_bug_2](https://user-images.githubusercontent.com/60902184/104623043-3108d680-564f-11eb-819c-f954308396f7.PNG)

**Additional context**
After downloading one of the incorrectly named outputs and renaming the file to be .gcode it appears to be normal gcode output.

**Comment by marciot** [comment]
@SynWillinger: This can be closed, right?

**Comment by SynWillinger** [comment]
@marciot yes, I recall this one having been resolved a while ago, and just double-checked in the current release. My bad for not getting this closed sooner.
