### ISSUE TITLE
Models auto-resizing without notification

### ISSUE THREAD

**Issue by SynWillinger** [SynDaverCO/symple-slicer#137]
**Describe the bug**
Not exactly a bug, but the template fits. When you load a model that is too large, it is automatically scaled down to fit the build area - but at the same time, it provides no notification that it was done. This has caused users to not notice it was scaled down, and then they printed their object to the wrong size.

**Details**
 - SympleSlicer Version: 1.0.16
 - Browser [e.g. chrome, safari]: Chrome

**To Reproduce**
1. Load a model that is larger than the build volume of the machine in at least one dimension
2. Select the object
3. Go to the scale manipulation menu
4. Observe that the scale % is not 100%, and has been reduced

**Expected behavior**
If the model is manipulated without explicit request from the user, a notification should be displayed

**Screenshots**

**Additional context**

**Comment by synsuiter** [comment]
issue is resolved. I am going to close.
