### ISSUE TITLE
Text correction

### ISSUE THREAD

**Issue by synsuiter** [SynDaverCO/symple-slicer#139]
We are still referring to the files as "G-code" in the options but we are defaulting them to ".gco".

This will confuse any new user. 

Since we are moving forward with ".gco", we should correct the options to match. 

![print_and_preview](https://user-images.githubusercontent.com/65256117/112663485-8109d380-8e1e-11eb-8ad0-def15ef21178.png)

**Comment by marciot** [comment]
@synsuiter: This is correct. The ".gco" is the file extension for G-code files, the same way as ".txt" is the extension for text files. You don't call text files ".txt" files.

**Comment by synsuiter** [comment]
@marciot ok, I will explain in the guide and hopefully they read it
