### ISSUE TITLE
Custom "home" positions

### ISSUE THREAD

**Issue by synsuiter** [SynDaverCO/symple-slicer#142]
**Is your feature request related to a problem? Please describe.**
No Problem.

**Describe the solution you'd like**
I would like to be able to save a custom position that my printer will move to after/when it "Auto Home"s. 

This could be convenient for customers because not every customer is going to want their printers in the same position for cleaning/servicing/etc.
Those who switch filament a lot can save a custom position that makes their tool head accessible. 
Those who clean glue off their bed frequently can save a position that gets the tool head out of the way and brings the bed forward. 
And Those who usually have a messy workspace can save a position that would move the bed and tool head out of they way so they can clean filament out from under their printer. 

**Describe alternatives you've considered**
Another menu with several positions predicted and pre-saved for their use. 

**Additional context**
Not a high priority, this could be for this printer and/or for future projects.

**Comment by marciot** [comment]
Without some pretty major changes to Marlin, this would require the firmware to be recompiled for each different homing position. So it likely won't get done.

**Comment by synsuiter** [comment]
Closing
