### ISSUE TITLE
Symple Slicer Guide images

### ISSUE THREAD

**Issue by synsuiter** [SynDaverCO/symple-slicer#149]
Broken Images:

These images are not appearing in the Guide, they might need to be added in due to an update or addition, or it may be a text thing I have not been able to find. 

1) [[figure:images/tools.PNG]]
2) [[figure:images/select_profiles3.png]]
3) [[figure:images/save-settings.png]]

**Comment by marciot** [comment]
@synsuiter: This can be closed, right?

**Comment by synsuiter** [comment]
Indeed! 😸
