### ISSUE TITLE
Add dual extruder UI controls

### ISSUE THREAD

**Issue by SynWillinger** [SynDaverCO/symple-slicer#158]
**Is your feature request related to a problem? Please describe.**
Currently, Symple Slicer lacks the ability to do dual extrusion due to controls for it not being implemented in the UI.

**Describe the solution you'd like**
Specifics of this implementation are still being discussed.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by synsuiter** [comment]
I am going to close this ticket out because we have now implemented these and are creating new tickets for specific corrections to the additions.
