### ISSUE TITLE
wifi printing error: addr is not defined

### ISSUE THREAD

**Issue by SynWillinger** [SynDaverCO/symple-slicer#159]
**Describe the bug**
In the current beta, if I try to send a sliced gcode to a machine, I get the following error:
![image](https://user-images.githubusercontent.com/60902184/166295731-59ecd4cd-0668-4349-96e4-64ee92b0f00f.png)

**Details**
 - SympleSlicer Version: beta 1.1.0 as of 5/2
 - Browser: Chrome

**To Reproduce**
1. Set up a machine in the Wifi Printing section
2. Slice a gcode
3. Select "send gcode to printer"

**Expected behavior**
no error should be encountered, and the gcode should be sent to the machine

**Screenshots**

**Additional context**
The same error is encountered if you try to update wireless firmware. No error is seen but nothing happens if I try to use "manage" from the "Wireless Printing" section

**Comment by synsuiter** [comment]
confirmed on my end
![wifi-error-confirmed](https://user-images.githubusercontent.com/65256117/166302729-79c921ae-5b42-4a4e-a562-6e5ff1c97e38.JPG)

**Comment by SynWillinger** [comment]
This issue has been corrected based on our testing.
