### ISSUE TITLE
PLA profile missing from NG2

### ISSUE THREAD

**Issue by synsuiter** [SynDaverCO/symple-slicer#168]
**Describe the bug**
PLA profile is not listed in the materials drop down for the NG2 printer

**Details**
 - Symple Slicer Version: 1.1.1 BETA
 - Browser : CHROME

**To Reproduce**
1. Load up SS beta.
2. Select the NG2 printer
3. observe the material list for that printer

**Expected behavior**
Even tho they are not custom for the NG2 yet, a stand-in PLA profile should be present like the others. 

**Screenshots**
![missing-pla](https://user-images.githubusercontent.com/65256117/185495165-ab31fe45-e0d6-4aac-bee8-68f420758543.JPG)

**Comment by marciot** [comment]
@synsuiter: There is no profile for PLA specified in "profile_lists.toml" for the NG2, hence the behavior in the UI is correct.
