### ISSUE TITLE
No support option for beginners

### ISSUE THREAD

**Issue by synsuiter** [SynDaverCO/symple-slicer#170]
**Describe the bug**
The "Beginners" setting level option has a "Support" section but does not show the Check box when expanded. It is effectively empty. 

**Details**
 - SympleSlicer Version: 1.1.1 BETA
 - Browser : Chrome

**To Reproduce**
1. open Symple Slicer
2. Go to the Advanced settings
3. Apply the setting level "Beginner" 
4. Select and apply a printer and a material
5. Go to the Slicing section and try to turn on the supports. 

**Expected behavior**
There should be the option to turn the support on and once turned on, no other settings will appear.
Simply an "ON" - "OFF" option. 

**Screenshots**
![missing-support-option](https://user-images.githubusercontent.com/65256117/185498196-4663c683-af4d-4558-ac9e-cffa314d9acf.JPG)

**Comment by marciot** [comment]
@synsuiter: This is because "support_enable" was missing from the beginner settings. I added it.

**Comment by synsuiter** [comment]
Gracias, closing ticket.
