### ISSUE TITLE
Models moving when sliced

### ISSUE THREAD

**Issue by synsuiter** [SynDaverCO/symple-slicer#171]
**Describe the bug**
When slicing more than one unique model, they will reposition themselves when you engage the "slice" function. 
This was confirmed with numerous model pairs, they only need to be different models. 

**Details**
 - SympleSlicer Version: 1.1.1 BETA
 - Browser: Chrome

**To Reproduce**
1. Open Symple Slicer
2. Select an AXI printer and any material profile and APPLY.
3. Load in at least 2 models that are NOT the same. 
4. Position them for slicing.
5. Slice those models
6. Observe that the slice does not match with where you positioned your models.

**Expected behavior**
The models should stay positioned where they were intended by the user. 

**Screenshots**
BEFORE SLICE
![before-slice](https://user-images.githubusercontent.com/65256117/185499572-af7800d2-4d9e-43e4-bf30-9c222f3edb45.JPG)
![before-slice2](https://user-images.githubusercontent.com/65256117/185499573-4f1ed65a-df7f-4ed6-9ce2-ca85d322711a.JPG)

AFTER SLICE
![after-slice](https://user-images.githubusercontent.com/65256117/185499605-261ea83b-d7b9-46f1-95ba-f72706eaecf0.JPG)
![after-slice2](https://user-images.githubusercontent.com/65256117/185499607-2db66a9e-0856-4872-9e98-e5742dc3bcfe.JPG)

**Comment by marciot** [comment]
@symsuiter: Have been unable to reproduce this.

**Comment by marciot** [comment]
@symsuiter: Export your settings and make sure nether mesh_rotation_matrix, mesh_position_x, mesh_position_y nor mesh_position_z are in the settings. If it is, it may override the positioning for objects.

**Comment by synsuiter** [comment]
Upon removing the following settings as a factor, the models still moved at time of slice. 

- mesh_position_x
- mesh_position_y
- mesh_positionz
- mesh_rotation_matrix

**Comment by synsuiter** [comment]
When I change all those settings to a value of "0", there is no change in the shifted position result when sliced.

**Comment by marciot** [comment]
@synsuiter: You should not change the values to zero. You should remove them altogether.

**Comment by synsuiter** [comment]
I did both, I was reporting that removing them AND changing them, make no difference.

**Comment by synsuiter** [comment]
Here are the profiles I have tested. 
[offset-tester.txt](https://github.com/SynDaverCO/symple-slicer/files/9396212/offset-tester.txt)
[offset-tester_changed.txt](https://github.com/SynDaverCO/symple-slicer/files/9396213/offset-tester_changed.txt)
[offset-tester_fixed.txt](https://github.com/SynDaverCO/symple-slicer/files/9396214/offset-tester_fixed.txt)
[offset-tester_removed.txt](https://github.com/SynDaverCO/symple-slicer/files/9396215/offset-tester_removed.txt)

**Comment by synsuiter** [comment]
Fixed!! :D closing ticket.
