### ISSUE TITLE
Drop Down profile Application required

### ISSUE THREAD

**Issue by synsuiter** [SynDaverCO/symple-slicer#176]
**Describe the bug**
When opening a new window of Symple Slicer, I am unable to import a custom toml file and then slice with it. I fist must apply a supported profile through the drop down before it registers that I have applied a printer. 

**Details**
 - SympleSlicer Version: Beta 1.1.1
 - Browser : Chrome

**To Reproduce**
1. open new Symple Slicer
2. import a custom TOML file and APPLY it
3. load in a model and go to slice
4. you will see a notification saying "Please apply a printer profile to slice

**Expected behavior**
the slicer should be able to accept and slice from a custom TOML file because it should contain the machine info for application.

**Screenshots**
![apply-printer-first_after-hist-wipe](https://user-images.githubusercontent.com/65256117/187507002-9ad4ed37-08fb-4d2c-b5f7-be3977f46841.PNG)
![apply-printer-first](https://user-images.githubusercontent.com/65256117/187507005-e3645378-a87b-4490-959f-25e9dc82a4f8.PNG)

**Comment by marciot** [comment]
@symsuiter: A fix for this has been uploaded
