### ISSUE TITLE
Visual error in Navigation Cube

### ISSUE THREAD

**Issue by synsuiter** [SynDaverCO/symple-slicer#184]
**Describe the bug**
The "back" and "front" walls of the cube become invisible after selecting the "back" option. 

**Details**
 - SympleSlicer Version: BETA 1.2.0.
 - Browser : google Chrome

**To Reproduce**
1. Open SS and navigate with the cube right click menu options. 

**Expected behavior**
walls should remain visible. 

**Screenshots**
![hollow-nav-cube](https://user-images.githubusercontent.com/65256117/195884359-72e5f698-a0dc-4ade-9608-fd4d15e4a802.PNG)

**Comment by marciot** [comment]
This one might be a web browser rendering bug and there may be nothing I can do about it. It's very peculiar.

**Comment by synsuiter** [comment]
I cant seem to replicate it now so I am going to close this out. we can reopen if it becomes in issue later.
