### ISSUE TITLE
Centering Error for larger models

### ISSUE THREAD

**Issue by synsuiter** [SynDaverCO/symple-slicer#188]
**Describe the bug**
When centering larger models, it places then on the top left, instead of in the middle.

Seems t affect models that come close to exceeding the AXI2 Bed limits. Not sure if that is relevant. 

**Details**
 - SympleSlicer Version: 1.2.0
 - Browser: Chrome

**To Reproduce**
1. Apply any printer and material profile
2. Load in a large model, I have attached an example model.
3. Try to center the model.

**Expected behavior**
Center model to build plate bed

**Screenshots**
This is how it "centers" now:
![dimensions](https://user-images.githubusercontent.com/65256117/199322096-9d42fbae-c39b-48c3-8ef9-748ad2fc6876.JPG)

This is the model shrunk down and centered, it centers correctly. 
![center-1 2 0](https://user-images.githubusercontent.com/65256117/199322100-73778985-f552-4035-adae-e458bddd0a82.JPG)

These are the size dimensions of the 1st larger model, it SHOULD have been able to center and print, it was not larger than the build plate, I excluded brim and skirt from the settings in case the UI was picking up on that causing the print to not fit. 
![off-center-1 2 0](https://user-images.githubusercontent.com/65256117/199322103-93006b1c-71ea-492f-a68a-67f9142e7e60.JPG)

**Comment by marciot** [comment]
@synsuiter: Can you attach the STL to this ticket?

**Comment by synsuiter** [comment]
My apologies, I meant to and completely forgot. 
[fullbed_wavytest-superfine.txt](https://github.com/SynDaverCO/symple-slicer/files/9954087/fullbed_wavytest-superfine.txt)

Change to .stl

**Comment by synsuiter** [comment]
fixed
