### ISSUE TITLE
Unable to generate Gcode with supports

### ISSUE THREAD

**Issue by synsuiter** [SynDaverCO/symple-slicer#190]
**Describe the bug**
Upon slicing a normal model with a normally applied Machine and Material profile, BUT THEN enabling the SUPPORTS the slicer generated 0 lines of code. 

**Details**
 - SympleSlicer Version: 1.2.0
 - Browser: Google Chrome, up to date. 
         - Browser history and data wiped. Error confirmed on multiple computers.

**To Reproduce**
1. Apply a profile
2. Load a model
3. Activate supports
4. slice and see redult

**Screenshots** Pictures Below 

![added-suport](https://user-images.githubusercontent.com/65256117/200383294-942c0631-1c9f-4756-bb75-8a3c3a1c3402.JPG)
![with-supports_sliced](https://user-images.githubusercontent.com/65256117/200383303-95259fb1-35e2-4489-8987-e4ea5d34bebc.JPG)

**Comment by synsuiter** [comment]
![s-log-001](https://user-images.githubusercontent.com/65256117/200383873-1a59be27-4363-456c-9ed7-ecec73ab11ea.JPG)
![s-log-002](https://user-images.githubusercontent.com/65256117/200383881-f6253af2-a64a-40ab-9516-f8daea439930.JPG)

**Comment by marciot** [comment]
@synsuiter: This appears to be a problem with CuraEngine requiring "support_enabled" to be presented in the command line before certain other settings. I have created a ticket upstream.

https://github.com/Ultimaker/CuraEngine/issues/1763

We can work around this on our end, although there is a posibility other settings may have similar requirements.

**Comment by marciot** [comment]
@synsuiter: Can this be closed?

**Comment by synsuiter** [comment]
Indeed, Issue has been resolved. Gracias
