### ISSUE TITLE
Extra Travel Moves

### ISSUE THREAD

**Issue by synsuiter** [SynDaverCO/symple-slicer#193]
**Describe the bug**
SS is adding extra travel moves to X00 Y00 each time the nozzles switch. 

**Details**
 - SympleSlicer Version: 1.2.0
 - Browser : google chrome

**To Reproduce**
1. Create a dual slice with both nozzles being used to print.
2. observe the preview travel lines.

I tried changing the setting "layer_start_x" and "layer_start_y" to the center of the bed (500x500) but that didn't change where it was traveling too. 

**Screenshots**
![dual-time-est](https://user-images.githubusercontent.com/65256117/201427032-7834a20c-6de3-4d9d-96ce-336ef1a2725e.JPG)

**Comment by marciot** [comment]
@synsuiter: This is a slice engine issue. I believe I've seen it before and Ultimaker Cura 4.12.1 does the same thing.

**Comment by marciot** [comment]
@synsuiter: Please test with "machine_extruder_end_pos_abs" set to "false" and possibly also "machine_extruder_start_pos_abs". I believe this is the setting that is causing the problem.

**Comment by synsuiter** [comment]
Will do

**Comment by synsuiter** [comment]
This works, I have pushed machine profile edits for the NG2. Will close when applied and confirmed.

**Comment by marciot** [comment]
@synsuiter: I pulled, but there are no changes to the profiles.

**Comment by synsuiter** [comment]
That..... Is because I forgot to Push them. My B. sending your way now.

**Comment by synsuiter** [comment]
This is solved, good find sir.
