### ISSUE TITLE
"All Cura Settings" not showing any settings

### ISSUE THREAD

**Issue by SynWillinger** [SynDaverCO/symple-slicer#198]
**Describe the bug**
Selecting "all cura settings" as the slicer settings results in no settings showing up 

**Details**
 - SympleSlicer Version: 1.2.0 Desktop build sent 12-2-22
 - Browser: none, desktop

**To Reproduce**
1. Go to Advanced Features in the page drop-down
2. Expand "User Interface" section
3. For "Slicer Settings" select "All Cura Settings"
4. Apply setting and wait for SS to reload
5. Go to "Slice Objets" in the page drop-down
6. See issue

**Expected behavior**
All settings should be available

**Screenshots**
![MicrosoftTeams-image (8)](https://user-images.githubusercontent.com/60902184/205400788-dccb7b14-b008-49c6-9c96-0bdc3e0e582d.png)

**Additional context**
Expert settings does work

**Comment by synsuiter** [comment]
also in axi machine view.
![all-settings-option_blank](https://user-images.githubusercontent.com/65256117/206284089-0b1f8774-87a3-47cd-93eb-fda0e460e984.JPG)

**Comment by synsuiter** [comment]
Confirmed Still Present. 12/9/22

**Comment by synsuiter** [comment]
corrected
