### ISSUE TITLE
Keep previous settings wording

### ISSUE THREAD

**Issue by SynWillinger** [SynDaverCO/symple-slicer#64]
**Is your feature request related to a problem? Please describe.**
wording is unclear in the startup profile select dialogue, with "keep previous settings"

**Describe the solution you'd like**
"last session settings"

**Describe alternatives you've considered**
additional text in the dialogue box that explains that the default selection (use whatever wording is used for it) will use whatever the user used in the last settings, and that picking another selection will load our latest defaults for what is selected.

**Additional context**

**Comment by marciot** [comment]
Can this be closed?
