### ISSUE TITLE
Settings descriptions getting truncated on Chrome

### ISSUE THREAD

**Issue by marciot** [SynDaverCO/symple-slicer#66]
**Describe the bug**

If the windows is close to the right edge of the screen, the tooltip will be sized incorrectly, causing the text to be unreadable.

**Details**
 - SympleSlicer Version: v1.0.3
 - Browser [e.g. chrome, safari]: Chrome

**To Reproduce**
1. Move the browser window near the right edge of the screen
2. Hover over "Enable print cooling"

**Expected behavior**
It should show the entire tool tip, but it does not.

**Screenshots**

![image](https://user-images.githubusercontent.com/6752228/83177572-88682f80-a0dc-11ea-9ba8-8ca68bff7c25.png)

**Additional context**

This is a Chrome bug, not a Symple Slicer bug. If you move the window away from the right side of the screen then the tooltip renders correctly. This cannot be fixed in Symple Slicer, but should be reported upstream.

**Comment by synsuiter** [comment]
@marciot Does this need further action from us? Are we keeping it open for reference?

**Comment by synsuiter** [comment]
I think we can close this out since we rearranged the UI anyway. We can open a new ticket if something like this happens in the new setup.
