### ISSUE TITLE
Save option default

### ISSUE THREAD

**Issue by synwest** [SynDaverCO/symple-slicer#68]
**Save option default**
After loading in an stl and go through the slicing process, the default save option has the file name as x.stl
Note: when the file type is changed to .gcode it stays .gcode
**Details**
 - SympleSlicer Version: v1.0.4
App
**To Reproduce**
1. Load in .stl
2. Run through slicing
3. Before clicking save, check save option file type

**Expected behavior**
I believe the save as file type should default to .gcode

**Comment by marciot** [comment]
Was the STL extension uppercase, by any chance? It seems like there was a bug where uppercase extensions were not being changed to .gcode

**Comment by synwest** [comment]
it is in fact uppercase

**Comment by marciot** [comment]
Fixed in v1.0.6, currently updated in beta:

https://syndaverco.github.io/slicer-beta/

**Comment by synwest** [comment]
Looks fixed
