### ISSUE TITLE
Update to edge gives white screen

### ISSUE THREAD

**Issue by Rosey1855** [SynDaverCO/symple-slicer#71]
**Describe the bug**
In edge when I refreshed the page to update to version 1.0.6. I just get a blank white screen. 

**Details**
Going from version 1.0.5 to 1.0.6.
Be on beta site, and refresh page to update to new version. 

**Expected behavior**
I should be able to update and use new beta version.

**Comment by marciot** [comment]
This should be fixed now. Let me know.

**Comment by Rosey1855** [comment]
Yep this is all good now.
