### ISSUE TITLE
Chrome not showing setting windows

### ISSUE THREAD

**Issue by Rosey1855** [SynDaverCO/symple-slicer#75]
**Describe the bug**
When I refresh the slicer in google chrome I get an error that says slicer is not defined. 

**Details**
 - SympleSlicer Version: 1.0.6.
 - Browser: Chrome

**To Reproduce**
1. Go to chrome
2. open slicer
3. Refresh page
4. See error and no setting options

**Expected behavior**
Should refresh to latest chrome version and be able to adjust settings

**Screenshots**

![slicer update](https://user-images.githubusercontent.com/61207846/85177783-08943780-b23a-11ea-9c4f-bb127fd19b4f.JPG)

**Comment by SynWillinger** [comment]
I can confirm I am not seeing this on beta or release

**Comment by Rosey1855** [comment]
Cleared cache and my issue went away.

**Comment by marciot** [comment]
I accidentally pushed a broken version of the updating tool to the beta branch. This hosed things in such a way that clearing the cache was the only way to restore things.
