### ISSUE TITLE
Slight placement difference between uses

### ISSUE THREAD

**Issue by SynWillinger** [SynDaverCO/symple-slicer#78]
**Describe the bug**
When generating gcode of the same model from both Chrome and Edge, the placement is ever so slightly different.

**Details**
 - SympleSlicer Version: 1.0.6
 - Browser: Chrome, and Edge

**To Reproduce**
1. Import model in chrome
2. Slice file and save
3. Import model in Edge
4. Slice file and save
5. Diff files

**Expected behavior**
Identical files should be generated

**Screenshots**
![Capture2](https://user-images.githubusercontent.com/60902184/85184908-f7a1f100-b24e-11ea-9281-223e1d319e7b.PNG)

**Additional context**
[Chrome_3DBenchy.gcode.txt](https://github.com/SynDaverCO/symple-slicer/files/4806964/Chrome_3DBenchy.gcode.txt)
[Edge_3DBenchy.gcode.txt](https://github.com/SynDaverCO/symple-slicer/files/4806963/Edge_3DBenchy.gcode.txt)

**Comment by SynWillinger** [comment]
My work machine received the new Chromium based version of Edge over the weekend, so I decided to test this again with the new version. Weirdly, this still seems to happen. On both browsers I refreshed the page, selected the machine and material profiles to ensure that was the same, loaded the same model and made no changes besides the file name post-slicing but before downloading the gcode.

20mm cube:
![chrome_vs_newedge_20mmcube](https://user-images.githubusercontent.com/60902184/85318796-d541ea80-b47d-11ea-92d6-05d4885e5705.PNG)

**Comment by SynWillinger** [comment]
I tried resetting browsing history on both browsers. Both wound up with different positions from each other, which were also different positions from before.

I then tried a couple tests using just Chrome:
I re-sliced the file after downloading the gcode but without changing anything. This resulted in identical gcode output as expected.
I also tested refreshing the page and then repeating all the same steps I had done before for loading the model and slicing it. This resulted in a location shift like we have been seeing here.

It would appear what we are seeing here is a small lack of repeatability in the placing of the model in the center as it is loaded, unrelated to browser.

**Comment by marciot** [comment]
Ohhh. Right. This actually is done intentionally. In order for the circle packing algorithm (which is used for placing objects in a non-intersecting way) it is necessary that the objects not all be in the same position. So I added a small random fudge when placing objects to keep them from overlapping at the origin.

**Comment by SynWillinger** [comment]
Ah. It is a little odd to have slightly varying positions when only one model is loaded. Could we have that not activate until the second model is loaded, or is it not worth the hassle and should this be a wontfix?

**Comment by marciot** [comment]
Leave it open for now. I have an idea on how to make it better.

**Comment by marciot** [comment]
This has been corrected in v1.0.7

**Comment by SynWillinger** [comment]
Tested, looks good. Closing issue.
