### ISSUE TITLE
Multiple "help" options with different information

### ISSUE THREAD

**Issue by SynWillinger** [SynDaverCO/symple-slicer#79]
**Is your feature request related to a problem? Please describe.**
There are two places on the main screen where you can see the words "help". One of these is a button at the top right of the screen that opens the guide in a separate window. The other location is in the drop down menu for selecting task groups on the bottom right. The one in the bottom right simply shows what the 3D view mouse controls are. Having these two separate sections with the same label but different information can be confusing to users.

**Describe the solution you'd like**
A link to the guide should be added to the results from selecting "Help" from the drop down in the lower right, so that if they use that instead of the help button at the top right they can still find the guide.

**Describe alternatives you've considered**
Changing the Help button at the top right to say "Guide" instead of "Help".

**Additional context**
![Capture3](https://user-images.githubusercontent.com/60902184/85307142-c0109000-b46c-11ea-9040-b82383d49dd2.PNG)

**Comment by marciot** [comment]
This has been corrected in v1.0.7

**Comment by SynWillinger** [comment]
I like the new functionality. Closing issue
