### ISSUE TITLE
Default model position

### ISSUE THREAD

**Issue by SynWillinger** [SynDaverCO/symple-slicer#80]
**Describe the bug**
Default position when models are loaded in is at 141,141. For a 280x280 build area, center should be 140,140.

**Details**
 - SympleSlicer Version: 1.0.7
 - Browser: Chrome

**To Reproduce**
1. Open Symple Slicer
2. Load a 20mm cube
3. Select object
4. Select "Move object"
5. Observe X and Y position values are both 141

**Expected behavior**
X and Y should both be 140

**Screenshots**
![default_position](https://user-images.githubusercontent.com/60902184/85771285-01a57300-b6d9-11ea-9e2a-2e74fe586b61.PNG)

**Comment by marciot** [comment]
The machine width and depth is 282 mm in the profiles, thus the positions are correct. If these values are incorrect, reopen this ticket in the profiles repo.
