### ISSUE TITLE
Model incorrectly labeled as in or out of bounds

### ISSUE THREAD

**Issue by SynWillinger** [SynDaverCO/symple-slicer#81]
**Describe the bug**
The model can be incorrectly marked as out of the build area when it is actually still in but close to the low end on X or Y. The model can be incorrectly marked as in the build area while outside of the build area extents in X and Y.

**Details**
 - SympleSlicer Version: 1.0.7
 - Browser: Chrome

**To Reproduce**

Outside build area:
1. Load 20mm cube
2. Open "slice objects" and set "build plate adhesion type" to "none" under "support & adhesion"
3. Click on model to select it
4. Open "scale object"
5. Scale X and Y to 280
6. Slice object and save gcode.
7. Open gcode, see that MAXX and MAXY are 280.8 according to the start of file comments, outside of the build area

Inside build area but marked as outside:
1. Load 20mm cube
2. Open "slice objects" and set "build plate adhesion type" to "none" under "support & adhesion"
3. Click on model to select it
4. Open "scale object"
5. Scale X and Y to 280
6. Open "move object"
7. Set X and Y locations to 140 (see #80 for more info on position)
8. Model goes red and "The red objects are outside the printable area" appears.

**Expected behavior**
Gcode should not generate movements outside the build area, and should allow models that are still within build area.

**Screenshots**

**Additional context**
Code that goes outside of build area:
[placement_test_bigflat.gcode.txt](https://github.com/SynDaverCO/symple-slicer/files/4833049/placement_test_bigflat.gcode.txt)

Code generated at positions for 140.1,140.1 showing the model should still be within limits at 140,140:
[placement_test2_bigflat.gcode.txt](https://github.com/SynDaverCO/symple-slicer/files/4833055/placement_test2_bigflat.gcode.txt)

**Comment by marciot** [comment]
Can't fix this one. The out-of-bounds detection while placing models applies only to the vertices in the STL file, not the generated GCODE (which isn't known until after the slicer runs). Hence, it is an approximation.

Once the model is sliced, there is an additional check on the GCODE and it will show a warning if the points are out-of-bounds.
