### ISSUE TITLE
Print Speed UI setting additions request

### ISSUE THREAD

**Issue by synsuiter** [SynDaverCO/symple-slicer#82]
**Is your feature request related to a problem? Please describe.**
There has been an issue with needing to reduce print speeds to improve ghosting, to make up the time I am planning to vary the speeds based on feature, allowing the infill to print faster. This means the customer will need access to those varied settings because it will no longer be handled under one settings.

**Describe the solution you'd like**
I would like to see these settings added to the "print speed" section.
**"Print Speed"** (To BE KEPT: This would only apply to speed settings that are NOT walls or infills or supports)
**"Wall Speed"** (this would be one value that would apply to BOTH the inner and outer wall)
**"Infill Speed"** (This would apply to infill speed)
**"Travel Speed"** (this would only apply to travel speeds)

**Describe alternatives you've considered**
Increasing speed overall reduces wall quality, decreasing the speeds reduced quality in corners but also made prints take much longer than would be expected by the market. We have also tested variations on Jerk and Acceleration, and while tuning those per material may help, it will not solve the issue for needed speed gain in the infill. 

**Additional context**
I hope you have a good day.

**Comment by marciot** [comment]
Pushed fix for this to beta v1.0.7
