### ISSUE TITLE
Other UI settings Addition request

### ISSUE THREAD

**Issue by synsuiter** [SynDaverCO/symple-slicer#84]
**Is your feature request related to a problem? Please describe.**
Adhesion can be effected by the initial layer height and since we do not offer different quality profiles, the customer will need to be able to adjust this settings as it compares to their other layer height changes.
Infill before walls is a settings that can help with thicker layered overhangs, it is a commonly used settings in the 3D printing community. 

**Describe the solution you'd like**
Please add:
**Infill before Walls** as a check box in the SHELL section
**Initial Layer Height** as value entry next to the layer height value

**Describe alternatives you've considered**
NO alternatives, these are being added to prevent an issue that could happen to a customer. 

**Additional context**
Gracias! 😃

**Comment by marciot** [comment]
Pushed this to beta.

**Comment by marciot** [comment]
@synsuiter: Can this ticket be closed?

**Comment by marciot** [comment]
@synsuiter: Can this be closed?

**Comment by synsuiter** [comment]
Sorry for the delay, looks good.
