### ISSUE TITLE
Changing speed through UI

### ISSUE THREAD

**Issue by synwest** [SynDaverCO/symple-slicer#85]
**Describe the bug**
Changing print speed in UI doesnt translate over to the profile correctly

**Details**
 - SympleSlicer Version:1.07
 - Browser: chrome app

**To Reproduce**
1. Load PLA profile
2. In "slice objects" change speed to 75mm/sec
3. Select slice
4. Export profile
5. Speed roofing, speed topbottom, speed wall  are all half of print speed

**Expected behavior**
All speed settings should be the same

**Comment by synwest** [comment]
# #82

**Comment by marciot** [comment]
Pushed fix for this to beta v1.0.7

**Comment by marciot** [comment]
@synwest: Can this ticket be closed?

**Comment by synwest** [comment]
I think so
