### ISSUE TITLE
Lay Flat Function

### ISSUE THREAD

**Issue by synsuiter** [SynDaverCO/symple-slicer#92]
So this issue is referring back to: lay flat button not working #8.

It was closed but I had a tech support call come in the other day and the user was having issues having their model lay flat, it would lay almost completely flat but then when they would begin the print it would print a small geometry instead of the full base and it was clear after looking again, that it was balancing on a smaller face that was near the bottom of the part, not the bottom flat base. 
I cannot get a screen shot or the model file because it was a model for a client of the user and they cannot share it with anyone. 
I can confirm they were using Google Chrome and did try and clear their browser history/cache and it didn't change anything. 

When they downloaded the browser installer version, they said it worked better, I am not sure why this is because its the exact same program.

I am going to leave this ticket open until the users tech support needs are met but I would like to track any further "Lay Flat" issues here in the future.

**Comment by marciot** [comment]
You need to ask users to simply apply a small rotation to the object and try again. The way the algorithm works is it finds the center of the object and picks the flat face of the convex hull directly below that point to use for the layflat. Rotating the object slightly will cause a different face to be chosen.
