### ISSUE TITLE
Filament runout ignored during gcode streaming

### ISSUE THREAD

**Issue by SynWillinger** [SynDaverCO/symple-slicer#95]
**Describe the bug**
If a filament runout is triggered during a print while gcode is streaming from Symple Slicer Desktop, there will be a short pause and the runout audio alert will play and the "Extruder 1 Filament Error" will display on the LCD. After a moment, however, the print will continue as though nothing happened.

**Details**
 - SympleSlicer Version: 7-13 test desktop build

**To Reproduce**
1. Slice a model and begin streaming gcode
2. Remove filament from the runout sensor, or have filament runout
3. See error

**Expected behavior**
Print should be paused until operator input is received, while also allowing for the filament to be changed out, like a filament runout acts when printing from USB drive.

**Screenshots**

**Additional context**

**Comment by marciot** [comment]
@SynWillinger: Can this ticket be closed?
