### ISSUE TITLE
"Select Profiles" button change

### ISSUE THREAD

**Issue by synsuiter** [SynDaverCO/symple-slicer#97]
**Is your feature request related to a problem? Please describe.**
some confusion on the button being needed to apply the profile

**Describe the solution you'd like**
change the "NEXT" button to say "APPLY" like the description

**Describe alternatives you've considered**
a description is already there with "apply" present and it wasn't clear enough so a button clarifying that it 'applies' the selections seems the simplest solution

**Additional context**
Have a good one :)

**Comment by marciot** [comment]
This is changed in beta

**Comment by marciot** [comment]
@synsuiter: Can this ticket be closed?
